from .node import node_container
from .inctement import inc
from typing import Iterable, Callable

class attr_value(node_container):
    def __init__(self, value):
        self.value = value
        super().__init__(pin_to_parent=False)
    
    def render(self):
        value = str(self.value)
        return '"' + value.replace('"', "&quot;") + '"'

class html_tag(node_container):
    close_tag: bool = True
    enter_space: bool = True

    _replace_attr_name: Callable[[str], str] = lambda _, s: s.removeprefix("_").replace("_", "-")

    def __init__(
        self,
        inner_text: str | node_container = "",
        *,
        _class: Iterable[node_container | str] = None,
        pin_to_parent = True,
        **attrs
    ):
        add = {}
        if _class:
            if isinstance(_class, str):
                add["_class"] = _class
            else:
                _class = " ".join([str(_c) for _c in _class])
                if _class:
                    add["_class"] = _class
    
        self.attrs = {k: self.prepare_value(v) for k, v in (attrs | add).items()}
        self.inner_text = self.prepare_value(inner_text)

        super().__init__(pin_to_parent=pin_to_parent)

    def prepare_value(self, value):
        if isinstance(value, node_container):
            value.unpin_from_parent()
        return value

    def render(self):
        kd = []
        kd.append(inc.enter_space)
        kd.append("<")
        kd.append(self.__class__.__name__)

        attrs_kb = []
        for key, value in self.attrs.items():
            if not isinstance(value, attr_value):
                value = attr_value(value)
            attrs_kb.append(self._replace_attr_name(key) +"="+str(value))
        if attrs_kb:
            kd.append(" ")
            kd.append(" ".join(attrs_kb))

        kd.append(">")

        if self.close_tag:
            kd_childs = []
            with inc:
                if (v := str(self.inner_text)):
                    if self.enter_space and not v.startswith(inc.enter_space): 
                        kd_childs.append(inc.enter_space)
                    kd_childs.append(v)
                for child in self.childs:
                    kd_childs.append(str(child))

            if kd_childs:
                kd += kd_childs

            if self.enter_space and kd_childs: kd.append(inc.enter_space)

            kd.append("</")
            kd.append(self.__class__.__name__)
            kd.append(">")

        return "".join(kd)

class _inline(html_tag):
    enter_space=False

class _open(html_tag):
    close_tag=False

class html(html_tag): ...
class head(html_tag): ...
class body(html_tag): ...
class div(html_tag): ...
class script(html_tag): ...
class style(html_tag): ...
class select(html_tag): ...
class option(html_tag): ...
class pre(html_tag): ...

class header(html_tag): ...
class footer(html_tag): ...
class main(html_tag): ...
class section(html_tag): ...
class article(html_tag): ...
class aside(html_tag): ...
class nav(html_tag): ...
class figure(html_tag): ...
class figcaption(html_tag): ...
class details(html_tag): ...
class summary(html_tag): ...
class fieldset(html_tag): ...
class form(html_tag): ...
class dialog(html_tag): ...

class ul(html_tag): ...
class ol(html_tag): ...
class li(html_tag): ...
class dl(html_tag): ...
class dt(html_tag): ...
class dd(html_tag): ...

class table(html_tag): ...
class thead(html_tag): ...
class tbody(html_tag): ...
class tfoot(html_tag): ...
class tr(html_tag): ...
class th(html_tag): ...
class td(html_tag): ...
class caption(html_tag): ...
class colgroup(html_tag): ...
class col(html_tag): ...

class img(_open): ...
class audio(html_tag): ...
class video(html_tag): ...
class source(_open): ...
class track(_open): ...
class canvas(html_tag): ...
class svg(html_tag): ...
class picture(html_tag): ...
class iframe(html_tag): ...

class input(_open): ...
class textarea(html_tag): ...
class button(html_tag): ...
class label(_inline): ...
class optgroup(html_tag): ...
class datalist(html_tag): ...

class h1(_inline): ...
class h2(_inline): ...
class h3(_inline): ...
class h4(_inline): ...
class h5(_inline): ...
class h6(_inline): ...
class p(_inline): ...
class a(_inline): ...
class span(_inline): ...
class strong(_inline): ...
class em(_inline): ...
class b(_inline): ...
class i(_inline): ...
class u(_inline): ...
class small(_inline): ...
class mark(_inline): ...
class abbr(_inline): ...
class code(_inline): ...
class var(_inline): ...
class samp(_inline): ...
class kbd(_inline): ...
class q(_inline): ...
class cite(_inline): ...
class dfn(_inline): ...
class time(_inline): ...
class label(_inline): ...
class title(_inline): ...

class meta(_open): ...
class link(_open): ...
class br(_open): ...
class wbr(_open): ...
class img(_open): ...
class source(_open): ...
class track(_open): ...
class base(_open): ...
class hr(_open): ...

class style_item(node_container):

    _replace_attr_name: Callable[[str], str] = lambda _, s: s.removeprefix("_").replace("_", "-")

    def __init__(self, selector, *items: node_container, _pin_to_parent=True, **attrs):
        super().__init__(pin_to_parent=_pin_to_parent)
        self.selector = selector
        self.attrs = attrs

        for item in items:
            if isinstance(item, node_container):
                self.add_child(item)

    def render(self):
        kb = []
        kb.append(inc.enter_space)
        kb.append(str(self.selector))
        kb.append(" {")
        kb_childs = []
        with inc:
            space = inc.enter_space
            for k,v in self.attrs.items():
                render_key = str(k)
                render_value = str(v)
                kb_childs.append(space + self._replace_attr_name(render_key.removeprefix(space)))
                kb_childs.append(": ")
                kb_childs.append(render_value)
                kb_childs.append(";")

            for child in self.childs:
                render_child = str(child)
                kb_childs.append(space + render_child.removeprefix(space))
        if kb_childs:
            kb += kb_childs
            kb.append(inc.enter_space)
        kb.append("}")

        return "".join(kb)